#
# Playground DB config (PostgresSQL)
#

default: &default
  host: localhost
  username: scoffey
  password: 1167Spartans

development:
  <<: *default
  adapter: postgresql
  database: playground_db

test:
  <<: *default
  adapter: postgresql

production:
  <<: *default
  adapter: postgresql
